export const faultCode: string[] = [
  "rm -rf /", "rm -rf", "sudo rm -rf", "sudo rm -rf --no-preserve-root",
  "while true; do :; done", ":(){ :|:& };:", 'system("rm -rf /");',
  'os.system("rm -rf /")', 'subprocess.call("rm -rf /", shell=True)',
  'exec("rm -rf /")', 'eval("rm -rf /")', 'require("child_process").exec("rm -rf /")',
  'child_process.execSync("rm -rf /")', 'fs.unlinkSync("/")', "while (true) {}",
  "for (;;);", "for(;;){}", "while (1);", "while(1) {}", "while True: pass",
  "for i in iter(int, 1): pass", "Set-Location -Path C:\\; Remove-Item -Path C:\\* -Recurse -Force",
  "():{ :|:& };:", "def fork_bomb(): import os; while True: os.fork()", "while(1) fork();",
  "while(true) { new Thread(() -> { while (true) {} }).start(); }", "fork();", "os.fork()",
  "os.fork() os.fork() os.fork()", 'subprocess.call("shutdown -h now", shell=True)',
  'subprocess.call("reboot", shell=True)', 'exec("shutdown -h now")', "shutdown -h now",
  "reboot", "shutdown -s -t 0", "shutdown -r -t 0", "format C:", "del /F /S /Q C:\\",
  "eval(", "exec(", "os.popen(", "subprocess.Popen(", "system(", 'require("child_process").exec(',
  "child_process.spawn(", "child_process.fork(", "os.remove(", "os.unlink(", "fs.rmSync(",
  "fs.unlinkSync(", "shutil.rmtree(", "del ", "rmdir ", "rm -r ", "bash -i >& /dev/tcp/",
  "nc -e /bin/sh", "netcat -e /bin/sh", "perl -e", "python -c 'import socket",
  "php -r 'system(\"nc", "mshta ", "powershell -nop -c", "import socket,subprocess,os",
  'os.system("nc', "wget http://", "curl http://", "Invoke-WebRequest", "scp ", "rsync ",
  "cat /etc/passwd", "cat /etc/shadow", "getent passwd", "getent shadow", "awk -F: '{print $1}' /etc/passwd",
  "find / -perm -4000", "chmod 777 /etc/shadow", "chown root:root /etc/shadow", "dd if=/dev/random of=/dev/sda",
  "mkfs.ext4 /dev/sda1", "mknod /dev/malicious c 1 3", 'echo "malware" > /etc/cron.daily/malware',
  "iptables -F", "iptables --flush", "iptables -P INPUT ACCEPT", "iptables -P OUTPUT ACCEPT",
  "iptables -P FORWARD ACCEPT", 'echo "root::0:0::/:/bin/bash" >> /etc/passwd',
  "useradd hacker -G root", "usermod -aG sudo hacker", "passwd hacker", "yes | rm -rf *",
  "mv /bin/bash /bin/bash.bak", "mv /bin/sh /bin/sh.bak", 'echo "evil_code" >> ~/.bashrc',
  "nohup rm -rf / &", "nohup :(){ :|:& };: &", "nohup shutdown -h now &", "nohup reboot &",
  "nohup format C: &", "nohup dd if=/dev/random of=/dev/sda &", "nohup mkfs.ext4 /dev/sda1 &"
];
